# Generated by Django 3.1.3 on 2021-03-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog1', models.TextField(blank=True, null=True)),
                ('blog2', models.TextField(blank=True, null=True)),
                ('blog3', models.TextField(blank=True, null=True)),
                ('blog4', models.TextField(blank=True, null=True)),
                ('blog5', models.TextField(blank=True, null=True)),
                ('posted_by', models.CharField(max_length=100)),
                ('blog_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
