# Generated by Django 3.1.3 on 2021-03-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.TextField(blank=True, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('content3', models.TextField(blank=True, null=True)),
                ('content4', models.TextField(blank=True, null=True)),
                ('content5', models.TextField(blank=True, null=True)),
                ('posted_by', models.CharField(max_length=100)),
                ('content_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('online', models.BooleanField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.listing')),
            ],
        ),
    ]
