# Generated by Django 3.1.3 on 2021-03-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
