# Generated by Django 3.1.3 on 2021-03-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210322_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infoblog',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
