# Generated by Django 3.1.3 on 2021-03-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='go_online',
            field=models.BooleanField(null=True),
        ),
    ]
