# Generated by Django 3.1.3 on 2021-03-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_content_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='name',
            new_name='blog_title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.infoblog'),
        ),
    ]
