# Generated by Django 3.1.3 on 2021-03-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210317_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='blog_title',
            new_name='blog_name',
        ),
    ]
