# Generated by Django 3.1.3 on 2021-05-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_infoblog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoblog',
            name='type',
        ),
    ]
