# Generated by Django 3.1.3 on 2021-03-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210317_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='title',
            new_name='blog_category',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='blog_name',
            new_name='blog_title',
        ),
    ]
