# Generated by Django 3.1.3 on 2021-05-19 14:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_infoblog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content4',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content5',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
