# Generated by Django 3.1.3 on 2021-07-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210519_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug_field',
            field=models.SlugField(allow_unicode=True, default='', max_length=200, verbose_name='slug_title'),
        ),
    ]
