# Generated by Django 3.1.3 on 2021-03-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_infoblog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='online',
        ),
    ]
