# Generated by Django 3.1.3 on 2021-07-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_content_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug_field',
            field=models.SlugField(allow_unicode=True, max_length=200, verbose_name='slug_title'),
        ),
    ]
