# Generated by Django 3.1.3 on 2021-07-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210708_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug_field',
            field=models.SlugField(max_length=200),
        ),
    ]
