# Generated by Django 3.1.3 on 2021-03-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseblog',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
