# Generated by Django 3.1.3 on 2021-03-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210322_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseblog',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
