# Generated by Django 3.1.3 on 2021-05-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_showcaseblog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseblog',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
