# Generated by Django 3.1.3 on 2021-05-19 14:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_showcaseblog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcaseblog',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
