# Generated by Django 3.1.3 on 2021-03-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutdeveloper',
            old_name='about1',
            new_name='About1',
        ),
        migrations.RenameField(
            model_name='aboutdeveloper',
            old_name='about2',
            new_name='About2',
        ),
        migrations.RenameField(
            model_name='aboutdeveloper',
            old_name='date_created',
            new_name='Date_created',
        ),
        migrations.RenameField(
            model_name='aboutdeveloper',
            old_name='title',
            new_name='Title',
        ),
    ]
