# Generated by Django 3.1.3 on 2021-03-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210308_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdeveloper',
            name='go_online',
            field=models.BooleanField(null=True),
        ),
    ]
