# Generated by Django 3.1.3 on 2021-03-22 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutdeveloper_go_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdeveloper',
            name='Date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
