# Generated by Django 3.1.3 on 2021-05-19 14:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20210322_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdeveloper',
            name='About1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutdeveloper',
            name='About2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
