# Generated by Django 3.1.3 on 2021-05-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20210519_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutdeveloper',
            old_name='About1',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='aboutdeveloper',
            name='About2',
        ),
    ]
