# Generated by Django 3.1.3 on 2021-05-19 14:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthwc',
            name='about_blog1',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='abouthwc',
            name='about_blog2',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
