# Generated by Django 3.1.3 on 2021-05-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_blog', '0002_auto_20210519_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abouthwc',
            old_name='about_blog1',
            new_name='about_blog',
        ),
        migrations.RemoveField(
            model_name='abouthwc',
            name='about_blog2',
        ),
    ]
